<a href="https://colab.research.google.com/github/Devsharma003/Dev/blob/main/randomforest_company.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Company_Data (1).csv to Company_Data (1).csv


In [ ]:
data=pd.read_csv('Company_Data (1).csv')

In [ ]:
data

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [ ]:
data.loc[data.Sales >=8.5,'sales']= 'high'
data.loc[data.Sales <8.5,'sales']= 'low'

In [ ]:
data.drop('Sales',1,inplace=True)

In [ ]:
data.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['US']= label_encoder.fit_transform(data['US'])
data['US'].unique()

array([1, 0])

In [ ]:
label_encoder = preprocessing.LabelEncoder()
data['Urban']= label_encoder.fit_transform(data['Urban'])

In [ ]:
label_encoder = preprocessing.LabelEncoder()
data['ShelveLoc']= label_encoder.fit_transform(data['ShelveLoc'])

In [ ]:
colnames = list(data.columns)
predictors = colnames[0:10]
target = colnames[10]

In [ ]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [ ]:
target

'sales'

In [ ]:
label_encoder = preprocessing.LabelEncoder()
data['sales']= label_encoder.fit_transform(data['sales'])

In [ ]:
X = data[predictors]
Y = data[target]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")

In [ ]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [ ]:
rf.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1892814334),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1721335690),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=33135511),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=892467068),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=97993014),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1126517885),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=483109635),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=545991169),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
             

In [ ]:
rf.classes_

array([0, 1])

In [ ]:
rf.n_classes_

2

In [ ]:
rf.n_outputs_

1

In [ ]:
data['rf_pred'] = rf.predict(X)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred'])

array([[143,   0],
       [  0, 257]])

# Now will try with 500 decision trees

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=500,criterion="entropy")

In [ ]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=500, n_jobs=2,
                       oob_score=True)

In [ ]:
data['rf_pred2'] = rf.predict(X)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred2'])

array([[143,   0],
       [  0, 257]])