<a href="https://colab.research.google.com/github/Devsharma003/Dev/blob/main/randomforest_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
import numpy as np
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Fraud_check (1).csv to Fraud_check (1).csv


In [ ]:
fraud=pd.read_csv('Fraud_check (1).csv')

In [ ]:
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [ ]:
fraud.loc[fraud['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
fraud.loc[fraud['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [ ]:
fraud.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good  
2   YES           Good  
3   YES           Good  
4    NO           Good

In [ ]:
fraud.head(2)

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good

In [ ]:
fraud.drop('Taxable.Income',1,inplace=True)

In [ ]:
fraud['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
fraud['Marital.Status']= label_encoder.fit_transform(fraud['Marital.Status'])
fraud['Marital.Status'].unique()

array([2, 0, 1])

In [ ]:
fraud.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [ ]:
fraud['Undergrad']= label_encoder.fit_transform(fraud['Undergrad'])
fraud['Undergrad'].unique()

array([0, 1])

In [ ]:
fraud.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [ ]:
fraud['Urban']= label_encoder.fit_transform(fraud['Urban'])
fraud['Urban'].unique()

array([1, 0])

In [ ]:
fraud.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [ ]:
colnames = list(fraud.columns)
predictors = colnames[0:5]
target = colnames[5]

In [ ]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [ ]:
target

'Taxable_Income'

In [ ]:
X = fraud[predictors]
Y = fraud[target]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [ ]:
fraud.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [ ]:
fraud['rf_pred'] = rf.predict(X)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(fraud['Taxable_Income'],fraud['rf_pred'])

array([[476,   0],
       [  0, 124]])